name: Staging -> Production
on:
  issue_comment:
    types: [created, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        shell: python
        id: parsing
        run: |
          import sys
          
          body = """${{ github.event.issue.body }}"""
          splited = body.split('\n')
          start = splited.index("```yml")+1
          end = splited.index("```")
          datasets=' '.join([i[2:] for i in splited[start:end]])
          sys.stdout.write(datasets)  
                  
      - name: test output
        run: echo "${{ steps.parsing.outputs.stdout }}"
