name: Staging -> Production
on:
  issue_comment:
    types: [created, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        shell: python
        run: |
          print("""${{ github.event.issue.title }}""")
          print("""${{ github.event.issue.body }}""")
