name: Staging -> Production
on:
  issue_comment:
    types: [created, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        shell: python
        run: |
          import re
          
          title="""${{ github.event.issue.title }}"""
          body="""${{ github.event.issue.body }}"""
          
          result = re.search('%s(.*)%s' % ('---', '---'), body).group(1)
          print(result)
